github = "https://github.com/oknozor/cocogitto-action"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]

pre_bump_hooks = [
    "echo {{version}} > version",
    "sh -c 'echo $TOTO'",
    "exit 1",
]

# Dummmy changes
# Dummmy changes
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "git checkout develop",
    "git rebase main",
    "sh -c 'echo {{version+1minor-pre}} > version'",
    "git add version",
    "git commit -m 'chore bump snapshot to {{version+1minor-pre}}'",
    "git push --force-with-lease",
]
