github = "https://github.com/oknozor/cocogitto-action"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]

pre_bump_hooks = [
    "echo {{version}} > version",
]

# Dummmy changes
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "git checkout develop",
    "git rebase main",
    "sh -c \"{{version+1minor-pre}} > version\"",
    "git add version",
    "coco chore 'bump snapshot to {{version+1minor-pre}}'",
    "git push",
]