github = "https://github.com/oknozor/cocogitto-action"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
]

pre_bump_hooks = [
    "echo {{version}} > version",
]

# A list of command to run AFTER creating a version.
# `{{version}}` will be interpretted as your target version
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "git checkout develop",
    "git rebase main",
    "echo '{{version+1minor-pre}}' > version",
    "git add version",
    "coco chore 'bump snapshot to {{version+1minor-pre}}'",
    "git push",
]