name: Conventional commit check
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional commit check
        uses: actions/cocogitto-action@v1