on: [push]

jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Conventional commits compliance
        uses: oknozor/cog-conventional-check@v0.5.8
        with:
           check: true
           check-latest-tag-only: true
           release: true
