name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Conventional commit check
        uses: oknozor/cocogitto-action@v1
        with:
          check: false

      - name: Generate Changelog
        run: cog changelog > ${{ github.workspace }}-CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
