name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: check conventional commit compliance
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Semver release
        id: release
        uses: oknozor/cocogitto-action@v1.2
        with:
          check: false
          release: true
          git-user: 'Cog Bot'
          git-user-email: 'mycoolproject@org.org'

      - name: Print version
        run: "echo '${{ steps.release.outputs.version }}'"