name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Install cocogitto
        uses: oknozor/cocogitto-action@main
        with:
          check: false

      - name: Generate Changelog
        run: cog changelog > GITHUB_CHANGELOG.md

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: GITHUB_CHANGELOG.txt
